services:
  tensorflow-jupyter:
    build: .
    container_name: tf_jupyter
    restart: unless-stopped

    ports:
      - "8888:8888"

    volumes:
      - .:/workspace/code
      - /mnt/d/pgn_output:/pgn_data:ro

    environment:
      RUN_RESCUE_MEMORY_SIZE_EXPERIMENT: "False"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    stdin_open: true
    tty: true
